### ISSUE TITLE
[FR] Consider adding "Folder" map

### ISSUE THREAD

**Issue by Moyf** [matthewturk/obsidian-sidecar-panel#9]
Currently this plugin can only use `tags` to assign the Note in sidebar:
![image](https://github.com/user-attachments/assets/d736fa09-9d43-4700-8c19-39fe62dbf80d)

If it could support mapping by "Path"(Folder) would be really helpful - this way, we can assign a note for all notes in a specific folder!

Here is an example from NoteToolbar:
![image](https://github.com/user-attachments/assets/c7f9acaa-26fb-4f38-bd2b-373c9e57949d)

Furthermore, it would be fantastic if the note path could include a drop-down list and an auto-complete feature!

**Comment by matthewturk** [comment]
Love this idea!  I'll work on it the next few days and get out a new release.  I'll ping back here if I have any questions.

**Comment by Moyf** [comment]
> Love this idea! I'll work on it the next few days and get out a new release. I'll ping back here if I have any questions.

Amazing! Thank you so much!

**Comment by matthewturk** [comment]
I will roll a release today or tomorrow!  I have repeatedly mixed up the *right* way to release, so I need to go over it and make sure it's right.  If the new version doesn't do what you're looking for, I'm happy to re-open the issue and work on it again.
